-- Expand firewall category coverage with additional first-party hosts and common service domains.

INSERT INTO public.firewall_domain_database (category, domain, company_id)
VALUES
  ('youtube', 'youtu.be', NULL),
  ('youtube', 'm.youtube.com', NULL),
  ('youtube', 'music.youtube.com', NULL),
  ('youtube', 'studio.youtube.com', NULL),
  ('youtube', 'youtube-nocookie.com', NULL),
  ('youtube', 'i.ytimg.com', NULL),
  ('youtube', 's.ytimg.com', NULL),
  ('youtube', 'yt3.ggpht.com', NULL),
  ('youtube', 'youtubei.googleapis.com', NULL),

  ('social', 'fbcdn.net', NULL),
  ('social', 'messenger.com', NULL),
  ('social', 'whatsapp.com', NULL),
  ('social', 'web.whatsapp.com', NULL),
  ('social', 'api.whatsapp.com', NULL),
  ('social', 'threads.net', NULL),
  ('social', 'cdninstagram.com', NULL),
  ('social', 'tiktokcdn.com', NULL),
  ('social', 'tiktokv.com', NULL),
  ('social', 'snapchat.com', NULL),
  ('social', 'pinterest.com', NULL),
  ('social', 'pinimg.com', NULL),
  ('social', 'linkedin.com', NULL),

  ('streaming', 'api-global.netflix.com', NULL),
  ('streaming', 'disney-plus.net', NULL),
  ('streaming', 'dssott.com', NULL),
  ('streaming', 'spotifycdn.com', NULL),
  ('streaming', 'scdn.co', NULL),
  ('streaming', 'twitchcdn.net', NULL),
  ('streaming', 'ttvnw.net', NULL),
  ('streaming', 'hulu.com', NULL),
  ('streaming', 'max.com', NULL),
  ('streaming', 'hbomax.com', NULL),
  ('streaming', 'primevideo.com', NULL),

  ('gaming', 'steamcommunity.com', NULL),
  ('gaming', 'steamstatic.com', NULL),
  ('gaming', 'steamusercontent.com', NULL),
  ('gaming', 'epicgamescdn.com', NULL),
  ('gaming', 'riotcdn.net', NULL),
  ('gaming', 'playvalorant.com', NULL),
  ('gaming', 'ea.com', NULL),
  ('gaming', 'origin.com', NULL),
  ('gaming', 'battle.net', NULL),
  ('gaming', 'blizzard.com', NULL),
  ('gaming', 'minecraft.net', NULL),
  ('gaming', 'roblox.com', NULL),
  ('gaming', 'discord.com', NULL),

  ('adult', 'xhamster.com', NULL),
  ('adult', 'redtube.com', NULL),
  ('adult', 'youporn.com', NULL),
  ('adult', 'xnxx.com', NULL),
  ('adult', 'spankbang.com', NULL),

  ('vpn', 'protonvpn.com', NULL),
  ('vpn', 'mullvad.net', NULL),
  ('vpn', 'privateinternetaccess.com', NULL),
  ('vpn', 'piavpn.com', NULL),
  ('vpn', 'hotspotshield.com', NULL),
  ('vpn', 'windscribe.com', NULL),
  ('vpn', 'cyberghostvpn.com', NULL),

  ('proxy', 'proxysite.com', NULL),
  ('proxy', 'croxyproxy.com', NULL),
  ('proxy', 'whoer.net', NULL),
  ('proxy', 'filterbypass.me', NULL),
  ('proxy', '4everproxy.com', NULL),
  ('proxy', 'zend2.com', NULL),

  ('torrent', 'torrentgalaxy.to', NULL),
  ('torrent', 'yts.mx', NULL),
  ('torrent', 'limetorrents.lol', NULL),
  ('torrent', 'rutracker.org', NULL),
  ('torrent', 'nyaa.si', NULL),
  ('torrent', 'qbittorrent.org', NULL),

  ('shopping', 'mercadolibre.com', NULL),
  ('shopping', 'temu.com', NULL),
  ('shopping', 'shein.com', NULL),
  ('shopping', 'walmart.com', NULL),
  ('shopping', 'target.com', NULL),
  ('shopping', 'bestbuy.com', NULL),
  ('shopping', 'etsy.com', NULL),

  ('ai-tools', 'perplexity.ai', NULL),
  ('ai-tools', 'poe.com', NULL),
  ('ai-tools', 'character.ai', NULL),
  ('ai-tools', 'copilot.microsoft.com', NULL),
  ('ai-tools', 'deepseek.com', NULL),
  ('ai-tools', 'midjourney.com', NULL),
  ('ai-tools', 'huggingface.co', NULL),

  ('dating', 'okcupid.com', NULL),
  ('dating', 'badoo.com', NULL),
  ('dating', 'happn.com', NULL),
  ('dating', 'grindr.com', NULL),
  ('dating', 'match.com', NULL),
  ('dating', 'pof.com', NULL)
ON CONFLICT (category, domain) DO NOTHING;
