// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';
const FALLBACK_SUPABASE_URL = 'https://invalid.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWYiOiJpbnZhbGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjAsImV4cCI6NDA3MDkwODgwMH0.invalid';

function getProjectRefFromUrl(url: string): string | null {
  try {
    const hostname = new URL(url).hostname;
    return hostname.split('.')[0] ?? null;
  } catch {
    return null;
  }
}

function getProjectRefFromPublishableKey(key: string): string | null {
  const segments = key.split('.');

  if (segments.length < 2) {
    return null;
  }

  try {
    const normalizedPayload = segments[1]
      .replace(/-/g, '+')
      .replace(/_/g, '/')
      .padEnd(Math.ceil(segments[1].length / 4) * 4, '=');
    const payload = JSON.parse(atob(normalizedPayload)) as { ref?: unknown };

    return typeof payload.ref === 'string' ? payload.ref : null;
  } catch {
    return null;
  }
}

function validateSupabaseConfiguration(url: string, publishableKey: string): string | null {
  if (!url || !publishableKey) {
    return 'Faltan variables de entorno de Supabase. Configura VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY en el entorno de build.';
  }

  const urlProjectRef = getProjectRefFromUrl(url);
  const keyProjectRef = getProjectRefFromPublishableKey(publishableKey);

  if (!urlProjectRef || !keyProjectRef) {
    return 'Configuracion de Supabase invalida: no se pudo validar el proyecto configurado.';
  }

  if (urlProjectRef !== keyProjectRef) {
    return `Configuracion de Supabase inconsistente: la URL apunta a "${urlProjectRef}" y la publishable key a "${keyProjectRef}".`;
  }

  return null;
}

const supabaseConfigurationError = validateSupabaseConfiguration(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

if (supabaseConfigurationError) {
  console.error(`[Supabase] ${supabaseConfigurationError}`);
}

const resolvedSupabaseUrl = supabaseConfigurationError ? FALLBACK_SUPABASE_URL : SUPABASE_URL;
const resolvedSupabasePublishableKey = supabaseConfigurationError
  ? FALLBACK_SUPABASE_PUBLISHABLE_KEY
  : SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(resolvedSupabaseUrl, resolvedSupabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});